name: "" # default name for the experiment, "" means logger (eg. wandb) will generate a unique name
seed: 52 # seed for random number generators in pytorch, numpy and python.random
num_workers: 16 # number of subprocesses to use for data loading.

# === 2. Specify defaults here. Defaults will be overwritten by equivalently named options in this file ===
defaults:
  - env: default
  - dataset: go-mf
  - features: ca_bb
  - encoder: puffin
  - decoder: default
  - transforms: default
  - callbacks: default
  - optimiser: adam
  - scheduler: none
  - trainer: gpu
  - extras: default
  - hydra: default
  - metrics: none
  - task: multilabel_graph_classification
  - paths: default
  - strategy: default
  - environment: default
  - logger: wandb # Also supported: tensorboard, wandb
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null
  - optional hparams: ${encoder}_${features}
  - _self_ # see: https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/. Adding _self_ at bottom means values in this file override defaults.

task_name: "train"

objective_type: "benchmark" # benchmark, unsupervised, contrastive, dual
lambda_w: 0.1  # dual
function_weight: 0.8  
unit_weight: 0
mutual_weight: 0.2
mutual_temp: 0.7
entropy_weight: 0
entropy_alpha: 1.0
entropy_beta: 0.3
tau: 0.1 # contrastive
alpha: 0.05 # contrastive

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null



